import { sentenceCards } from "./sentences.mjs";

/**
 * Practice material is intentionally data-only. The UI presents one target at
 * a time and captures the learner's real chord; there are no quiz questions.
 */
export const concepts = {
  chord: {
    title: "Một lần bấm",
    instruction:
      "Đặt ngón tay lên các phím đang sáng, nhấn chúng cùng lúc, rồi thả hết để viết.",
  },
  vowel: {
    title: "Bắt đầu với nguyên âm",
    instruction:
      "Các phím giữa bàn phím viết a, o, e, u và i. Nhấn các phím đang sáng cùng lúc, rồi thả.",
  },
  onset: {
    title: "Thêm chữ đầu",
    instruction:
      "Bấm các phím bên trái cùng với phím giữa để viết trọn một tiếng.",
  },
  tone: {
    title: "Thêm dấu",
    instruction:
      "Bấm thêm phím dấu trong cùng lần bấm. Hãy nhìn chữ cần viết và bấm cả cụm một lượt.",
  },
  coda: {
    title: "Thêm chữ cuối",
    instruction:
      "Bấm thêm các phím bên phải trong cùng lần bấm. V7 sẽ sắp chữ và đặt dấu đúng chỗ.",
  },
  context: {
    title: "Viết câu tự nhiên",
    instruction:
      "Bạn có thể viết từng tiếng hoặc viết hai tiếng trong một lần bấm. Hãy chọn cách nhanh và thoải mái nhất.",
  },
  repair: {
    title: "Chọn cách viết rồi sửa chỗ sai",
    instruction:
      "Đây là bài tập thao tác: viết hai tiếng trong một lần bấm, chọn cách viết được yêu cầu, rồi sửa riêng phần đang sáng.",
  },
  orthography: {
    title: "Chọn đúng cách viết",
    instruction:
      "Cùng một nhóm phím có thể tạo ra chữ khác nhau tùy nguyên âm và cách ghép. Nhìn chữ mẫu, bấm cả cụm một lượt.",
  },
  punctuation: {
    title: "Ngắt câu",
    instruction:
      "Dùng cụm phím dấu câu sau khi viết xong ý. Dấu sẽ được đặt ngay sau phần chữ hiện có.",
  },
  control: {
    title: "Điều khiển bài viết",
    instruction:
      "Một số lần bấm không viết chữ: chúng giúp bạn quay lại hoặc chèn khoảng cách khi đang soạn câu.",
  },
};

const card = (id, concept, target, stroke, keys, note = "") => ({
  id,
  concept,
  target,
  strokes: [stroke],
  keys,
  note,
  kind: "deterministic",
});

const controlCard = (id, target, stroke, keys, note = "") => ({
  ...card(id, "control", target, stroke, keys, note),
  kind: "control",
});

// The first group covers every vowel shape, every initial family, all finals,
// all Vietnamese tone marks, and the punctuation/control strokes used by the
// production editor. These are deliberately explicit so a curriculum review
// can see which physical operation each card exercises.
const coverageCards = [
  card("v-y", "vowel", "y", "AOEU", ["KeyC", "KeyV", "KeyN", "KeyM"]),
  card("v-ia", "vowel", "ia", "OEU", ["KeyV", "KeyN", "KeyM"]),
  card("v-ua", "vowel", "ua", "AEU", ["KeyC", "KeyN", "KeyM"]),
  card("v-ua-open", "vowel", "ưa", "AOE", ["KeyC", "KeyV", "KeyN"]),
  card("o-ca", "onset", "ca", "KA", ["KeyS", "KeyC"]),
  card("o-cha", "onset", "cha", "KHA", ["KeyS", "KeyR", "KeyC"]),
  card("o-da", "onset", "da", "KWRA", ["KeyS", "KeyD", "KeyF", "KeyC"]),
  card("o-dda", "onset", "đa", "TKA", ["KeyW", "KeyS", "KeyC"]),
  card("o-pha", "onset", "pha", "TPA", ["KeyW", "KeyE", "KeyC"]),
  card("o-pin", "onset", "pin", "PEUR", ["KeyE", "KeyN", "KeyM", "KeyJ"]),
  card("o-ga", "onset", "ga", "TKPWA", [
    "KeyW",
    "KeyS",
    "KeyE",
    "KeyD",
    "KeyC",
  ]),
  card("o-ha", "onset", "ha", "HA", ["KeyR", "KeyC"]),
  card("o-gia", "onset", "gia", "KWHA", ["KeyS", "KeyD", "KeyR", "KeyC"]),
  card("o-kha", "onset", "khá", "KHRAL", [
    "KeyS",
    "KeyR",
    "KeyF",
    "KeyC",
    "KeyO",
  ]),
  card("o-na", "onset", "na", "TPHA", ["KeyW", "KeyE", "KeyR", "KeyC"]),
  card("o-ngo", "onset", "ngô", "TPWOE", [
    "KeyW",
    "KeyE",
    "KeyD",
    "KeyV",
    "KeyN",
  ]),
  card("o-ra", "onset", "ra", "RA", ["KeyF", "KeyC"]),
  card("o-sa", "onset", "sa", "KPA", ["KeyS", "KeyE", "KeyC"]),
  card("o-tha", "onset", "tha", "THA", ["KeyW", "KeyR", "KeyC"]),
  card("o-tra", "onset", "tra", "TRA", ["KeyW", "KeyF", "KeyC"]),
  card("o-xa", "onset", "xa", "WRA", ["KeyD", "KeyF", "KeyC"]),
  card("g-qua", "orthography", "qua", "SKA", ["KeyA", "KeyS", "KeyC"]),
  card("g-mua", "orthography", "mua", "PHAEU", [
    "KeyE",
    "KeyR",
    "KeyC",
    "KeyN",
    "KeyM",
  ]),
  card("g-mua-open", "orthography", "mưa", "PHAOE", [
    "KeyE",
    "KeyR",
    "KeyC",
    "KeyV",
    "KeyN",
  ]),
  card("g-tia", "orthography", "tia", "TOEU", ["KeyW", "KeyV", "KeyN", "KeyM"]),
  card("g-tua", "orthography", "tua", "TAEU", ["KeyW", "KeyC", "KeyN", "KeyM"]),
  card("g-bia", "orthography", "bia", "PWOEU", [
    "KeyD",
    "KeyE",
    "KeyV",
    "KeyN",
    "KeyM",
  ]),
  card("g-chia", "orthography", "chia", "KHOEU", [
    "KeyS",
    "KeyR",
    "KeyV",
    "KeyN",
    "KeyM",
  ]),
  card("f-bao", "coda", "bao", "PWAF", ["KeyE", "KeyD", "KeyC", "KeyU"]),
  card("f-bai", "coda", "bài", "PWAFPG", [
    "KeyE",
    "KeyD",
    "KeyC",
    "KeyU",
    "KeyI",
    "KeyL",
  ]),
  card("f-bam", "coda", "bám", "PWAPL", [
    "KeyE",
    "KeyD",
    "KeyC",
    "KeyI",
    "KeyO",
  ]),
  card("f-bang", "coda", "bang", "PWAFR", [
    "KeyE",
    "KeyD",
    "KeyC",
    "KeyU",
    "KeyJ",
  ]),
  card("f-mang", "coda", "mang", "PHAFR", [
    "KeyE",
    "KeyR",
    "KeyC",
    "KeyU",
    "KeyJ",
  ]),
  card("f-manh", "coda", "mạch", "PHARPBLG", [
    "KeyE",
    "KeyR",
    "KeyC",
    "KeyJ",
    "KeyI",
    "KeyK",
    "KeyO",
    "KeyL",
  ]),
  card("f-bat", "tone", "bát", "PWARBL", [
    "KeyE",
    "KeyD",
    "KeyC",
    "KeyJ",
    "KeyK",
    "KeyO",
  ]),
  card("f-bat-heavy", "tone", "bạt", "PWARBLG", [
    "KeyE",
    "KeyD",
    "KeyC",
    "KeyJ",
    "KeyK",
    "KeyO",
    "KeyL",
  ]),
  card("t-mo-sac", "tone", "mó", "PHOL", ["KeyE", "KeyR", "KeyV", "KeyO"]),
  card("t-mo-huyen", "tone", "mò", "PHOG", ["KeyE", "KeyR", "KeyV", "KeyL"]),
  card("t-mo-hoi", "tone", "mỏ", "PHOB", ["KeyE", "KeyR", "KeyV", "KeyK"]),
  card("t-mo-nga", "tone", "mõ", "PHOLG", [
    "KeyE",
    "KeyR",
    "KeyV",
    "KeyO",
    "KeyL",
  ]),
  card("t-mo-nang", "tone", "mộ", "PHOEBG", [
    "KeyE",
    "KeyR",
    "KeyV",
    "KeyN",
    "KeyK",
    "KeyL",
  ]),
  card("p-period", "punctuation", ".", "TP-PL", [
    "KeyW",
    "KeyE",
    "KeyI",
    "KeyO",
  ]),
  card("p-comma", "punctuation", ",", "KW-BG", [
    "KeyS",
    "KeyD",
    "KeyK",
    "KeyL",
  ]),
  card("p-question", "punctuation", "?", "KW-PL", [
    "KeyS",
    "KeyD",
    "KeyI",
    "KeyO",
  ]),
  card("p-exclamation", "punctuation", "!", "TP-BG", [
    "KeyW",
    "KeyE",
    "KeyK",
    "KeyL",
  ]),
  controlCard(
    "control-undo",
    "quay lại lần bấm trước",
    "*",
    ["Space"],
    "Trong trình soạn thật, * hoàn tác lần bấm gần nhất.",
  ),
  controlCard(
    "control-space",
    "khoảng cách",
    "S-P",
    ["KeyA", "KeyI"],
    "Dùng S-P khi cần chèn khoảng cách rõ ràng giữa hai phần chữ.",
  ),
];

export const cards = [
  card("v-a", "vowel", "a", "A", ["KeyC"]),
  card("v-o", "vowel", "o", "O", ["KeyV"]),
  card("v-e", "vowel", "e", "E", ["KeyN"]),
  card("v-u", "vowel", "u", "U", ["KeyM"]),
  card("v-i", "vowel", "i", "EU", ["KeyN", "KeyM"]),
  card("v-aw", "vowel", "ă", "AE", ["KeyC", "KeyN"]),
  card("v-aa", "vowel", "â", "AO", ["KeyC", "KeyV"]),
  card("v-ee", "vowel", "ê", "AU", ["KeyC", "KeyM"]),
  card("v-oo", "vowel", "ô", "OE", ["KeyV", "KeyN"]),
  card("v-ow", "vowel", "ơ", "OU", ["KeyV", "KeyM"]),
  card("v-uw", "vowel", "ư", "AOU", ["KeyC", "KeyV", "KeyM"]),
  card("o-ma", "onset", "ma", "PHA", ["KeyE", "KeyR", "KeyC"]),
  card("o-ba", "onset", "ba", "PWA", ["KeyE", "KeyD", "KeyC"]),
  card("o-ta", "onset", "ta", "TA", ["KeyW", "KeyC"]),
  card("o-la", "onset", "la", "HRA", ["KeyR", "KeyF", "KeyC"]),
  card("o-nha", "onset", "nha", "TPRA", ["KeyW", "KeyE", "KeyF", "KeyC"]),
  card("o-cho", "onset", "cho", "KHO", ["KeyS", "KeyR", "KeyV"]),
  card("t-ma", "tone", "má", "PHAL", ["KeyE", "KeyR", "KeyC", "KeyO"]),
  card("t-ma2", "tone", "mà", "PHAG", ["KeyE", "KeyR", "KeyC", "KeyL"]),
  card("t-ma3", "tone", "mả", "PHAB", ["KeyE", "KeyR", "KeyC", "KeyK"]),
  card("t-ma4", "tone", "mã", "PHALG", [
    "KeyE",
    "KeyR",
    "KeyC",
    "KeyO",
    "KeyL",
  ]),
  card("t-ma5", "tone", "mạ", "PHABG", [
    "KeyE",
    "KeyR",
    "KeyC",
    "KeyK",
    "KeyL",
  ]),
  card("c-ban", "coda", "ban", "PWAR", ["KeyE", "KeyD", "KeyC", "KeyJ"]),
  card("c-bang", "coda", "bang", "PWAFR", [
    "KeyE",
    "KeyD",
    "KeyC",
    "KeyU",
    "KeyJ",
  ]),
  card("c-banh", "coda", "bánh", "PWARPL", [
    "KeyE",
    "KeyD",
    "KeyC",
    "KeyJ",
    "KeyI",
    "KeyO",
  ]),
  card("c-lam", "coda", "làm", "HRAPG", [
    "KeyR",
    "KeyF",
    "KeyC",
    "KeyI",
    "KeyL",
  ]),
  card(
    "c-mat",
    "coda",
    "mát",
    "PHARBL",
    ["KeyE", "KeyR", "KeyC", "KeyJ", "KeyK", "KeyO"],
    "Để viết “mát”, bấm cả cụm BL bên phải trong cùng một lần.",
  ),
  ...coverageCards,
  {
    id: "x-nay-troi",
    concept: "repair",
    target: "nay trời",
    strokes: ["TPHA*EFBLT"],
    keys: [
      "KeyW",
      "KeyE",
      "KeyR",
      "KeyC",
      "Space",
      "KeyN",
      "KeyU",
      "KeyK",
      "KeyO",
      "KeyP",
    ],
    note: "Bấm Space cùng các phím còn lại để viết hai tiếng trong một lần.",
    kind: "inference",
    islands: ["", "na0tro2"],
    selectionIndex: 0,
    piecemeal: {
      targetFromRight: 1,
      entryStroke: "T",
      entryLabel: "T-",
      entryKeys: ["KeyW"],
      replacementTarget: "mà",
      replacementStroke: "PHAG",
      replacementKeys: ["KeyE", "KeyR", "KeyC", "KeyL"],
    },
  },
  {
    id: "x-dep-lam",
    concept: "repair",
    target: "đẹp lắm",
    strokes: ["#STKWR*UFGTS"],
    keys: [
      "KeyQ",
      "KeyA",
      "KeyW",
      "KeyS",
      "KeyD",
      "KeyF",
      "Space",
      "KeyM",
      "KeyU",
      "KeyL",
      "KeyP",
      "Semicolon",
    ],
    note: "Sau lần bấm đầu, hệ thống sẽ đưa ra vài cách viết để bạn chọn.",
    kind: "inference",
    islands: ["", "dde7la1"],
    selectionIndex: 1,
    piecemeal: {
      targetFromRight: 2,
      entryStroke: "P",
      entryLabel: "P-",
      entryKeys: ["KeyE"],
      replacementTarget: "ba",
      replacementStroke: "PWA",
      replacementKeys: ["KeyE", "KeyD", "KeyC"],
    },
  },
  {
    id: "x-sang-nay",
    concept: "repair",
    target: "sáng nay",
    strokes: ["STKPA*UFPL"],
    keys: [
      "KeyA",
      "KeyW",
      "KeyS",
      "KeyE",
      "KeyC",
      "Space",
      "KeyM",
      "KeyU",
      "KeyI",
      "KeyO",
    ],
    note: "Lần này hãy chọn cách viết thứ ba, rồi sửa phần đang sáng.",
    kind: "inference",
    islands: ["", "sa1na0"],
    selectionIndex: 2,
    piecemeal: {
      targetFromRight: 1,
      entryStroke: "T",
      entryLabel: "T-",
      entryKeys: ["KeyW"],
      replacementTarget: "mà",
      replacementStroke: "PHAG",
      replacementKeys: ["KeyE", "KeyR", "KeyC", "KeyL"],
    },
  },
  {
    id: "x-ma-ho",
    concept: "repair",
    target: "mà họ",
    strokes: ["PHA*EFB"],
    keys: ["KeyE", "KeyR", "KeyC", "Space", "KeyN", "KeyU", "KeyK"],
    note: "Hãy chọn cách viết thứ tư, sau đó đưa con trỏ đến phần thứ hai.",
    kind: "inference",
    islands: ["", "ma0ho2"],
    selectionIndex: 3,
    piecemeal: {
      targetFromRight: 2,
      entryStroke: "P",
      entryLabel: "P-",
      entryKeys: ["KeyE"],
      replacementTarget: "ba",
      replacementStroke: "PWA",
      replacementKeys: ["KeyE", "KeyD", "KeyC"],
    },
  },
  {
    id: "x-uong-bia",
    concept: "repair",
    target: "uống bia",
    strokes: ["*EUPTSD"],
    keys: ["Space", "KeyN", "KeyM", "KeyI", "KeyP", "Semicolon", "KeyT"],
    note: "Hãy chọn cách viết thứ năm rồi sửa phần đang sáng bằng một lần bấm mới.",
    kind: "inference",
    islands: ["", "0u0bi0"],
    selectionIndex: 4,
    piecemeal: {
      targetFromRight: 1,
      entryStroke: "T",
      entryLabel: "T-",
      entryKeys: ["KeyW"],
      replacementTarget: "mà",
      replacementStroke: "PHAG",
      replacementKeys: ["KeyE", "KeyR", "KeyC", "KeyL"],
    },
  },
  {
    id: "x-huong-sua",
    concept: "repair",
    target: "mà họ",
    strokes: ["PHA*EFB"],
    keys: ["KeyE", "KeyR", "KeyC", "Space", "KeyN", "KeyU", "KeyK"],
    note: "Bài này luyện phím H- để chọn phần cần sửa.",
    kind: "inference",
    islands: ["", "ma0ho2"],
    selectionIndex: 0,
    piecemeal: {
      targetFromRight: 1,
      entryStroke: "H",
      entryLabel: "H-",
      entryKeys: ["KeyR"],
      replacementTarget: "mà",
      replacementStroke: "PHAG",
      replacementKeys: ["KeyE", "KeyR", "KeyC", "KeyL"],
    },
  },
  {
    id: "x-dau-sua",
    concept: "repair",
    target: "mà họ",
    strokes: ["PHA*EFB"],
    keys: ["KeyE", "KeyR", "KeyC", "Space", "KeyN", "KeyU", "KeyK"],
    note: "Bài này luyện cụm TK- để chọn phần sửa ở xa hơn.",
    kind: "inference",
    islands: ["", "ma0ho2"],
    selectionIndex: 0,
    piecemeal: {
      targetFromRight: 2,
      entryStroke: "TK",
      entryLabel: "TK-",
      entryKeys: ["KeyW", "KeyS"],
      replacementTarget: "ba",
      replacementStroke: "PWA",
      replacementKeys: ["KeyE", "KeyD", "KeyC"],
    },
  },
  ...sentenceCards,
];

const byId = new Map(cards.map((item) => [item.id, item]));

export function getCard(id) {
  return byId.get(id) ?? null;
}

export function publicCard(item) {
  return {
    id: item.id,
    concept: item.concept,
    target: item.target,
    strokes: item.strokes,
    keys: item.keys,
    note: item.note,
    kind: item.kind,
    instruction: concepts[item.concept],
    selectionIndex: item.selectionIndex,
    piecemeal: item.piecemeal,
    category: item.category,
    pairs: item.pairs,
  };
}
